services:
  db:
    image: postgres:16-alpine
    container_name: flowers-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dockerpassword
      POSTGRES_DB: flowers_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_final:/var/lib/postgresql/data

volumes:
  postgres_data_final:
